export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const CHANGE_TOTAL = "CHANGE_TOTAL";
export const SET_FILTERS = "SET_FILTERS";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const AUTH_USER = "AUTH_USER";